#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/opt/homebrew/share/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/andygill/Desktop/acca_central"
export "FLUTTER_FRAMEWORK_SWIFT_PACKAGE_PATH=/Users/andygill/Desktop/acca_central/ios/Flutter/ephemeral/Packages/.packages/FlutterFramework"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=1.1.0"
export "FLUTTER_BUILD_NUMBER=11"
export "DART_DEFINES=VUtfT0REU19BUElfS0VZPXVrb19saXZlXzhmYmFiZDkzYjQ4YTE5ZmNkZWMwNWViZDFkNDEwYWRj,U1BPUlRNT05LU19BUElfVE9LRU49dzBONHF4YVk1dEQ0WjlTbzRrVlFiWm9GWWdhTnZMejBMN3FpQ1JsQjRTaE5RdUF2d0xocHJXNUpTMm93,QVBJX0ZPT1RCQUxMX0tFWT1mMDJlMDk2Mzc1NmEyY2MwZTBhMWI0M2IwMmM5MTIyYw==,T0REU19BUElfS0VZPTQ4ZjE0NjFjZGI2ZjQ1MmNjMDFhMzVkOGNmMTk3OWJm,RkxVVFRFUl9WRVJTSU9OPTMuNDQuOQ==,RkxVVFRFUl9DSEFOTkVMPXN0YWJsZQ==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049NmIxODJkMmM3NQ==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049NWEyYTZhNDJjYw==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My4xMi4y"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=false"
export "TREE_SHAKE_ICONS=true"
export "PACKAGE_CONFIG=/Users/andygill/Desktop/acca_central/.dart_tool/package_config.json"
